import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const packetPath = path.join(root, "ops/metal-print-vip/proof-order-packet.json");
const packet = JSON.parse(fs.readFileSync(packetPath, "utf8"));
const masterPath = path.join(root, packet.uploadMaster.relativePath);
assert.ok(fs.existsSync(masterPath), "upload master is missing");
const bytes = fs.readFileSync(masterPath);
assert.equal(bytes.length, packet.uploadMaster.bytes, "upload master byte size drifted");
assert.equal(crypto.createHash("sha256").update(bytes).digest("hex"), packet.uploadMaster.sha256, "upload master SHA-256 drifted");
const sips = execFileSync("sips", ["-g", "pixelWidth", "-g", "pixelHeight", "-g", "format", "-g", "space", "-g", "hasAlpha", masterPath], { encoding: "utf8" });
const field = (name: string) => sips.match(new RegExp(`\\b${name}:\\s*(.+)`))?.[1]?.trim();
assert.equal(Number(field("pixelWidth")), packet.uploadMaster.width);
assert.equal(Number(field("pixelHeight")), packet.uploadMaster.height);
assert.equal(field("format"), packet.uploadMaster.format);
assert.match(field("space") ?? "", /RGB/i);
assert.equal(field("hasAlpha"), "no");
assert.ok(fs.existsSync(packet.sourceMaster.absolutePath), "mounted source master is missing");
const sourceBytes = fs.readFileSync(packet.sourceMaster.absolutePath);
assert.equal(crypto.createHash("sha256").update(sourceBytes).digest("hex"), packet.sourceMaster.sha256, "mounted source SHA-256 drifted");
assert.equal(packet.configuration.widthMm, 600);
assert.equal(packet.configuration.heightMm, 600);
assert.equal(packet.configuration.quantity, 1);
assert.equal(packet.configuration.surface, "glossy");
assert.equal(packet.configuration.frame, "none");
assert.equal(packet.configuration.border, "none");
assert.equal(packet.configuration.hangingHardware, "aluminium rails");
assert.equal(packet.paymentControl.purchaseAuthorized, false);
assert.equal(packet.paymentControl.stopBeforeFinalPurchase, true);
assert.ok(packet.paymentControl.landedCeilingJpy <= 40_000);
assert.equal(packet.currentBrowserEvidence.authenticated, true);
assert.equal(packet.currentBrowserEvidence.visibleCartItems, 1);
assert.equal(packet.currentBrowserEvidence.configurationVerified, true);
assert.equal(packet.currentBrowserEvidence.addressStepReached, true);
assert.equal(packet.currentBrowserEvidence.purchaseCompleted, false);
assert.equal(packet.currentBrowserEvidence.displayedTotalJpy, packet.lastObservedQuote.displayedTotalJpy);
assert.equal(packet.lastObservedQuote.evidenceClass, "CURRENT_PLATFORM_CART_AND_ADDRESS_CHECKOUT_QUOTE");
console.log("metal-print proof order packet: PASS — master hash/metadata, 60cm current authenticated cart, address-step quote, payment stop");
