import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { metalPrintConsultationExpiresAt, qualifyMetalPrintConsultation, rankMetalPrintPreflightDemand, type MetalPrintConsultation } from "../src/lib/metal-print-consultation";
import { createMetalPrintContactVerificationToken, verifyMetalPrintContactVerificationToken } from "../src/lib/metal-print-contact-verification.server";

process.env.METAL_PRINT_IDENTITY_SECRET = "synthetic-identity-secret-at-least-32-characters";

const base: MetalPrintConsultation = { email: "collector@example.com", editionId: "VIP-METAL-2026-07-NATURA", workTitle: "Deus sive Natura", spaceType: "home", budgetBand: "330k_plus", purchaseTiming: "within_90d", decisionRole: "decision_maker", dossierRequested: true, purchaseIntentIndicated: true, contactConsent: true };
const qualified = qualifyMetalPrintConsultation(base);
assert.equal(qualified.qualified, true);
assert.equal(qualified.pipelineValueJpy, 330_000);
const preflight = qualifyMetalPrintConsultation({ ...base, editionId: "CATALOG-WORK:example" }, "preflight_required");
assert.equal(preflight.qualified, false, "catalog preflight request must not enter qualified pipeline before an approved Offer exists");
assert.equal(preflight.pipelineValueJpy, 0);
assert.ok(preflight.reasons.some((reason) => reason.includes("formal Offer")));
const rankedPreflight = rankMetalPrintPreflightDemand([
  ...Array.from({ length: 3 }, (_, index) => ({ editionId: "CATALOG-WORK:alpha", workTitle: "Alpha", offerState: "preflight_required", contactVerifiedAt: `2026-08-0${index + 1}` })),
  { editionId: "CATALOG-WORK:beta", workTitle: "Beta", offerState: "preflight_required", contactVerifiedAt: "2026-08-01" },
  { editionId: "CATALOG-WORK:ignored", workTitle: "Ignored", offerState: "preflight_required" },
  { editionId: "VIP-METAL-2026-07-NATURA", workTitle: "Deus sive Natura", offerState: "approved", contactVerifiedAt: "2026-08-01" },
]);
assert.equal(rankedPreflight[0]?.editionId, "CATALOG-WORK:alpha");
assert.equal(rankedPreflight[0]?.verifiedRequests, 3);
assert.equal(rankedPreflight[0]?.readyForOfferPreflight, true);
assert.equal(rankedPreflight[1]?.readyForOfferPreflight, false);
assert.equal(rankedPreflight.length, 2, "unverified or approved-Offer records contaminated catalog demand ranking");
assert.equal(qualifyMetalPrintConsultation({ ...base, budgetBand: "undecided" }).pipelineValueJpy, 0);
assert.equal(qualifyMetalPrintConsultation({ ...base, purchaseTiming: "exploring" }).qualified, false);
assert.equal(qualifyMetalPrintConsultation({ ...base, decisionRole: "influencer" }).qualified, false);
assert.equal(qualifyMetalPrintConsultation({ ...base, purchaseIntentIndicated: false }).qualified, false);
const origin = new Date("2026-07-20T00:00:00.000Z");
assert.equal(metalPrintConsultationExpiresAt(origin, "within_30d").toISOString(), "2026-08-19T00:00:00.000Z");
assert.equal(metalPrintConsultationExpiresAt(origin, "within_90d").toISOString(), "2026-10-18T00:00:00.000Z");

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const api = fs.readFileSync(path.join(root, "src/app/api/metal-print/consultation/route.ts"), "utf8");
const form = fs.readFileSync(path.join(root, "src/components/MetalPrintConsultationForm.tsx"), "utf8");
const redis = fs.readFileSync(path.join(root, "src/lib/metal-print-redis.server.ts"), "utf8");
const verificationRoute = fs.readFileSync(path.join(root, "src/app/api/metal-print/consultation/verify/route.ts"), "utf8");
const acceptanceRoute = fs.readFileSync(path.join(root, "src/app/api/metal-print/consultation/accept/route.ts"), "utf8");
const resumeRoute = fs.readFileSync(path.join(root, "src/app/api/metal-print/consultation/resume/route.ts"), "utf8");
const checkoutRoute = fs.readFileSync(path.join(root, "src/app/api/metal-print/checkout/route.ts"), "utf8");
assert.ok(api.includes("saveMetalPrintConsultation"), "durable save missing");
assert.ok(api.includes("getApprovedMetalPrintOffer(editionId)"), "catalog Offer approval is not checked");
assert.ok(api.includes('offerState = approvedOffer ? "approved"'), "unapproved catalog requests are not separated from approved Offers");
assert.ok(api.includes("qualifyMetalPrintConsultation(consultation, offerState)"), "qualification ignores Offer approval state");
assert.ok(api.includes("saveMetalPrintConsultationNotification"), "consultation notification result is not persisted");
assert.ok(api.includes('createHmac("sha256", identitySecret)'), "PII-safe identity deduplication missing");
assert.ok(api.includes("METAL_PRINT_IDENTITY_SECRET"), "identity secret gate missing");
assert.ok(api.includes("contactConsent !== true"), "explicit consent gate missing");
assert.ok(api.includes("dossierRequested !== true"), "explicit Dossier request gate missing");
assert.ok(api.includes('typeof body?.purchaseIntentIndicated !== "boolean"'), "provisional purchase-intent answer gate missing");
assert.ok(api.includes("invalid_origin"), "origin gate missing");
assert.ok(api.includes("METAL_ATTRIBUTION_FIELDS"), "attribution allowlist missing");
assert.ok(api.includes("isMetalPrintVerificationTraffic"), "verification consultation traffic is not isolated");
assert.ok(api.includes("verification_traffic_not_accepted"), "verification consultation rejection is missing");
assert.ok(api.indexOf("verification_traffic_not_accepted") < api.indexOf("saveMetalPrintConsultation({"), "verification traffic must be rejected before durable save");
assert.ok(api.indexOf("verification_traffic_not_accepted") < api.indexOf("sendEmail({"), "verification traffic must be rejected before notification");
assert.ok(api.includes("createMetalPrintContactVerificationToken"), "contact verification token is not created");
assert.ok(api.includes("verificationRequired: true"), "unverified consultation is not declared pending");
assert.ok(api.includes("consultationToken: null"), "unverified contact receives a checkout-capable token");
assert.ok(api.includes("checkoutAvailable: false"), "unverified contact can open Checkout");
assert.ok(verificationRoute.includes("verifyMetalPrintConsultationContact"), "verification route does not promote verified contact evidence");
assert.ok(verificationRoute.includes("createMetalPrintConsultationToken"), "verified qualified contact cannot resume Checkout");
assert.ok(!verificationRoute.includes('searchParams.set("consultationToken"'), "verified capability token leaked into the query string");
assert.ok(verificationRoute.includes('new URL("/chat", siteUrl())'), "verified contact resumes on a page without the consultation form");
assert.ok(verificationRoute.includes('resumeDestination.searchParams.set("work"'), "verified contact cannot recover the selected Edition");
assert.ok(verificationRoute.includes('consultation.workTitle || fixedEdition?.title'), "verified catalog consultation loses its selected work title");
assert.ok(verificationRoute.includes('resumeDestination.searchParams.set("workId", catalogWorkId)'), "verified catalog consultation loses its selected work id");
assert.ok(!verificationRoute.includes('? "Deus sive Natura"'), "verification resume still hardcodes the four-work title chain");
assert.ok(verificationRoute.includes("resumeDestination.hash"), "verified consultation capability is not kept in the URL fragment");
assert.ok(acceptanceRoute.includes("explicit_acceptance_required"), "post-review acceptance rejection is missing");
for (const field of ["dossierAccepted", "purchaseIntentConfirmed", "proofDisclosureAccepted", "madeToOrderTermsAccepted"]) assert.ok(acceptanceRoute.includes(`body?.${field} !== true`), `${field} is not explicitly required`);
assert.ok(acceptanceRoute.includes("acceptMetalPrintDossier"), "post-review Dossier acceptance is not persisted");
assert.ok(resumeRoute.includes("verifyMetalPrintConsultationToken"), "stored consultation cannot be cryptographically resumed");
assert.ok(resumeRoute.includes("invalid_origin"), "resume endpoint lacks same-origin protection");
assert.ok(resumeRoute.includes("acceptanceComplete"), "resume endpoint does not recover four-part acceptance state");
assert.ok(resumeRoute.includes("getApprovedMetalPrintOffer"), "resume endpoint can expose Checkout without current Offer approval");
for (const field of ["dossierAcceptedAt", "purchaseIntentConfirmedAt", "proofDisclosureAcceptedAt", "madeToOrderTermsAcceptedAt"]) assert.ok(checkoutRoute.includes(field), `Checkout opens without ${field}`);
assert.ok(form.includes("...attribution"), "consultation attribution persistence missing");
assert.ok(form.includes("window.location.hash"), "verified contact cannot resume the qualified browser state");
assert.ok(form.includes("window.history.replaceState"), "verified capability fragment is not cleared after use");
assert.ok(form.includes("sessionStorage.getItem(storageKey)"), "refresh or Checkout cancel loses the consultation capability");
assert.ok(form.includes('fetch("/api/metal-print/consultation/resume"'), "stored capability is trusted without server revalidation");
assert.ok(checkoutRoute.includes('new URL("/chat", siteUrl())'), "Stripe cancel does not return to the consultation form");
assert.ok(checkoutRoute.includes('searchParams.set("checkout", "cancelled")'), "Stripe cancel return state is missing");
assert.ok(form.includes('useState("")'), "qualification fields must start without an implicit answer");
assert.ok(form.includes("qualificationComplete"), "consultation submit is not gated on explicit qualification answers");
assert.ok(form.includes("isCatalogCandidate && !checkoutAvailable"), "approved catalog Offer remains trapped in preflight UI");
assert.ok(form.includes("METAL_PRINT_SIGNATURE_FORMAT"), "approved catalog Offer lacks its bound 600mm Dossier format");
assert.ok(form.includes("この一点の非公開Dossier"), "Dossier acceptance copy missing");
assert.ok(form.includes("購入を具体的に検討します"), "explicit purchase intent copy missing");
assert.ok(form.match(/<option value="" disabled>/g)?.length === 4, "all four qualification selectors need explicit-choice placeholders");
assert.ok(form.includes("disabled={!qualificationComplete"), "submit button does not enforce explicit qualification answers");
const chat = fs.readFileSync(path.join(root, "src/pages/chat.tsx"), "utf8");
assert.ok(chat.includes("METAL_CAMPAIGN_OPTIONS"), "generic VIP chat entry has no edition selection step");
assert.ok(chat.includes("metal_edition_selected"), "edition selection analytics missing");
assert.ok(chat.includes("!metalCampaignEditionId"), "generic VIP chat cannot recover from missing work attribution");
assert.ok(form.includes("metal_consultation_submitted") === false, "form must not emit analytics directly");
assert.ok(!form.includes("posthog"), "PII form must not access PostHog");
assert.ok(redis.includes("CONSULTATION_LUA"), "consultation record and stage index are not atomic");
assert.ok(redis.includes("minimum4xPassed"), "4x pipeline threshold missing");
assert.ok(redis.includes("strong10xPassed"), "10x strong-go threshold missing");
assert.ok(redis.includes("dossierAccepted"), "Dossier acceptance summary missing");
assert.ok(redis.includes("purchaseIntent"), "purchase intent summary missing");
assert.ok(redis.includes("zremrangebyscore"), "expired consultation cleanup missing");
assert.ok(redis.includes("consultation-identity"), "identity deduplication index missing");
assert.ok(redis.includes("byCampaign"), "anonymous campaign pipeline summary missing");
assert.ok(redis.includes("byPlacement"), "anonymous placement pipeline summary missing");
assert.ok(redis.includes("pipelineValueJpy += 330_000"), "qualified placement pipeline value is missing");
assert.ok(redis.includes("preflightRequested"), "catalog preflight demand is not separately observable");
assert.ok(redis.includes("preflightDemandByWork") && redis.includes("offerPreflightCandidates"), "catalog demand cannot drive autonomous Offer expansion");
assert.ok(redis.includes("unapproved catalog requests remain preflight demand with zero pipeline value"), "pipeline evidence boundary omits catalog preflight requests");
assert.ok(redis.includes("consultation-notification:"), "durable consultation notification record missing");
assert.ok(redis.includes("notificationFailures"), "notification failures are not summarized for operations");
assert.ok(api.includes("saveMetalPrintContactVerificationDelivery"), "contact verification delivery result is not persisted");
assert.ok(redis.includes("contactVerificationFailures"), "contact verification delivery failures are not summarized");
assert.ok(redis.includes("contactVerificationSent"), "successful contact verification deliveries are not summarized");
assert.ok(form.includes("verificationDeliveryFailed"), "verification delivery failure is silent in the UI");
assert.ok(redis.includes("verifiedRecords"), "unverified consultations are not excluded from pipeline aggregation");
assert.ok(redis.includes("paidVerified"), "unverified paid IDs can contaminate the matured close-rate cohort");
assert.ok(redis.includes("VERIFY_CONTACT_LUA"), "contact verification transition is not atomic");
assert.ok(redis.includes("ACCEPT_DOSSIER_LUA"), "post-review Dossier acceptance transition is not atomic");
assert.ok(redis.includes('typeof record?.dossierAcceptedAt === "string"'), "Dossier request can contaminate accepted count");
assert.ok(redis.includes('typeof record?.purchaseIntentConfirmedAt === "string"'), "provisional intent can contaminate confirmed purchase intent");
assert.ok(form.includes("postReviewDossierAccepted") && form.includes("postReviewPurchaseIntent"), "post-review confirmation UI is missing");
assert.ok(form.includes("postReviewProofDisclosureAccepted") && form.includes("postReviewMadeToOrderTermsAccepted"), "proof and made-to-order acknowledgements are missing");
assert.ok(redis.includes("record.proofDisclosureAcceptedAt = ARGV[4]") && redis.includes("record.madeToOrderTermsAcceptedAt = ARGV[4]"), "four-part acceptance is not persisted atomically");
assert.ok(form.includes("SELECTED WORK DOSSIER"), "post-review acceptance has no actual Dossier terms above it");
for (const term of ["価格状態", "実物proofは未承認", "配送条件", "変更・取消", "12営業日"]) assert.ok(form.includes(term), `Dossier term missing: ${term}`);

const verificationPayload = { consultationId: "123e4567-e89b-12d3-a456-426614174000", expiresAt: "2099-01-01T00:00:00.000Z" };
const verificationToken = createMetalPrintContactVerificationToken(verificationPayload);
assert.deepEqual(verifyMetalPrintContactVerificationToken(verificationToken), verificationPayload);
assert.equal(verifyMetalPrintContactVerificationToken(`${verificationToken}x`), null, "tampered verification token accepted");

console.log("metal-print consultation: PASS — qualification, consent, origin, durable campaign/placement summaries, no PII analytics");
