import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const api = fs.readFileSync(path.join(root, "src/app/api/metal-print/event/route.ts"), "utf8");
const client = fs.readFileSync(path.join(root, "src/lib/metal-print-funnel-client.ts"), "utf8");
const redis = fs.readFileSync(path.join(root, "src/lib/metal-print-redis.server.ts"), "utf8");
const chat = fs.readFileSync(path.join(root, "src/pages/chat.tsx"), "utf8");
assert.ok(api.includes("invalid_origin"));
assert.ok(api.includes("rateLimit"));
assert.ok(api.includes("METAL_FUNNEL_EVENTS.includes"));
assert.ok(client.includes("crypto.randomUUID"));
assert.ok(client.includes('"metal_home_view"'));
assert.ok(client.includes('"metal_home_cta_click"'));
assert.ok(!client.includes("email"));
assert.ok(redis.includes("no email, IP, or conversation text"));
assert.ok(redis.includes("zremrangebyscore"));
assert.ok(redis.includes("summarizeMetalPrintFunnel"));
assert.ok(redis.includes("placementStorageKey"), "placement-level attribution must use bounded aggregate keys");
assert.ok(redis.includes("byPlacement"), "source/content placement aggregates are missing");
assert.ok(redis.includes("encodeURIComponent(JSON.stringify"), "placement dimensions must be safely encoded in Redis keys");
assert.ok(redis.includes('typeof member === "string" ? JSON.parse(member) : member'), "Redis JSON responses must support decoded objects");
assert.ok(redis.includes('startsWith("verification_")'), "synthetic verification traffic must be isolated");
assert.ok(chat.includes('if (isMetalPrintEntry) recordMetalFunnelEvent("metal_chat_start"'), "direct-to-chat entries are not counted as chat starts");
const home = fs.readFileSync(path.join(root, "src/components/realm/RealmHome.tsx"), "utf8");
assert.ok(home.includes('recordMetalFunnelEvent("metal_home_view"'), "owned home impressions are not measured");
assert.equal((home.match(/recordMetalFunnelEvent\("metal_home_cta_click"/g) ?? []).length, 2, "both owned home CTAs must record clicks");
assert.ok(chat.includes('if (metalPrintEntry && userTurn === 1) recordMetalFunnelEvent("metal_first_message"'), "typed first messages are not counted");
assert.ok(chat.includes('productId === "vip-metal-print" && !metalFunnelActivatedRef.current'), "conversation-detected metal intent must activate the sales funnel");
assert.ok(chat.includes('capture("metal_funnel_activated_from_conversation"'), "conversation funnel activation must be observable");
assert.equal((chat.match(/recordMetalFunnelEvent\("metal_first_message"/g) ?? []).length, 2, "first-message recording must cover direct and conversation-detected entries exactly once each");
console.log("metal-print first-party funnel: PASS — allowlist, origin/rate gates, anonymous session, JP/EN placement aggregates, rolling Redis summary, no PII/text");
