import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Stripe from "stripe";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const checkoutRoute = fs.readFileSync(path.join(root, "src/app/api/metal-print/checkout/route.ts"), "utf8");
const webhookRoute = fs.readFileSync(path.join(root, "src/app/api/metal-print/webhook/route.ts"), "utf8");
const redisAdapter = fs.readFileSync(path.join(root, "src/lib/metal-print-redis.server.ts"), "utf8");
const offerLocks = fs.readFileSync(path.join(root, "src/lib/metal-print-offers.server.ts"), "utf8");
const consultationRoute = fs.readFileSync(path.join(root, "src/app/api/metal-print/consultation/route.ts"), "utf8");
const consultationForm = fs.readFileSync(path.join(root, "src/components/MetalPrintConsultationForm.tsx"), "utf8");
const consultationResumeRoute = fs.readFileSync(path.join(root, "src/app/api/metal-print/consultation/resume/route.ts"), "utf8");
const assuranceAudit = fs.readFileSync(path.join(root, "scripts/audit-metal-print-assurance.ts"), "utf8");
const connectivityProbe = fs.readFileSync(path.join(root, "scripts/probe-metal-print-production-connectivity.ts"), "utf8");
const fulfillmentRoute = fs.readFileSync(path.join(root, "src/app/api/metal-print/fulfillment/route.ts"), "utf8");
const verificationRoute = fs.readFileSync(path.join(root, "src/app/api/metal-print/verification/route.ts"), "utf8");
const productionE2eRunner = fs.readFileSync(path.join(root, "scripts/run-metal-print-production-e2e.ts"), "utf8");
const vendorOrderRunner = fs.readFileSync(path.join(root, "scripts/prepare-metal-print-vendor-order.ts"), "utf8");
const shippingPolicy = fs.readFileSync(path.join(root, "src/lib/metal-print-shipping-policy.ts"), "utf8");

const stripe = new Stripe("sk_test_placeholder");
const secret = "whsec_metal_print_test";
const payload = JSON.stringify({ id: "evt_test", object: "event", type: "checkout.session.completed", data: { object: {} } });
const header = stripe.webhooks.generateTestHeaderString({ payload, secret, timestamp: 1_783_900_000 });
const verified = stripe.webhooks.constructEvent(payload, header, secret, 10 ** 10);
assert.equal(verified.id, "evt_test");
assert.throws(() => stripe.webhooks.constructEvent(`${payload} `, header, secret, 10 ** 10), /signature/i);

assert.ok(checkoutRoute.includes("sameOrigin(request)"), "checkout CSRF origin gate missing");
assert.ok(checkoutRoute.includes("METAL_PRINT_VERIFIED_SHIPPING_COUNTRIES"), "checkout is not bound to the verified vendor coverage");
assert.ok(shippingPolicy.includes('worldwideClaimAllowed: false'), "worldwide fulfilment is overclaimed");
assert.ok(shippingPolicy.includes('neutralShipping: "EU_ONLY"'), "WhiteWall neutral-shipping restriction is missing");
assert.ok(checkoutRoute.includes("getApprovedMetalPrintOffer"), "offer approval gate missing");
assert.ok(checkoutRoute.includes("idempotencyKey: orderId"), "Stripe checkout idempotency key missing");
assert.ok(checkoutRoute.includes("offerApprovalToken, offerApprovedAt"), "Checkout does not preserve the approved Offer snapshot");
assert.ok(checkoutRoute.includes("releaseMetalPrintReservation"), "reservation compensation missing");
assert.ok(checkoutRoute.includes("PAYMENT_CONFIRMATION_GRACE_MS = 72 * 60 * 60 * 1000"), "delayed payment confirmation grace missing");
assert.ok(checkoutRoute.includes("reserveMetalPrint(editionId, orderId, reservationGraceUntil)"), "Redis reservation does not use payment confirmation grace");
assert.ok(checkoutRoute.includes("expires_at: Math.floor(checkoutExpiresAt.getTime() / 1000)"), "Stripe Checkout expiry is not separated from Redis confirmation grace");
assert.ok(webhookRoute.includes("request.text()"), "raw webhook body is not preserved");
assert.ok(webhookRoute.includes('request.headers.get("stripe-signature")'), "Stripe signature header missing");
assert.ok(webhookRoute.includes("session.amount_total !== offer.amountJpy"), "webhook amount verification missing");
assert.ok(webhookRoute.includes("getMetalPrintOfferFromApprovalSnapshot"), "paid webhook depends on mutable current Offer approval");
assert.ok(webhookRoute.includes('event.type === "charge.refunded"'), "production refund event missing");
assert.ok(webhookRoute.includes("applyMetalPrintRefund"), "production refund transition missing");
assert.ok(redisAdapter.includes("PXAT"), "reservation TTL missing");
assert.ok(redisAdapter.includes("CONFIRM_LUA"), "atomic payment confirmation missing");
assert.ok(redisAdapter.includes("if redis.call('EXISTS', KEYS[6]) == 1 then return 2 end"), "payment-intent idempotency missing");
assert.ok(redisAdapter.includes("REFUND_LUA"), "atomic refund retirement missing");
assert.ok(redisAdapter.includes("FULFILL_LUA"), "atomic fulfillment transition missing");
assert.ok(redisAdapter.includes("record.fulfillmentState == 'fulfilled'"), "refund does not distinguish fulfilled inventory");
assert.ok(redisAdapter.includes("redis.call('DEL', KEYS[1])"), "unfulfilled full refund cannot release inventory");
assert.ok(redisAdapter.includes("if fullRefund then"), "partial refund incorrectly changes serial availability");
assert.ok(redisAdapter.includes("zremrangebyscore"), "expired pipeline cleanup missing");
assert.ok(redisAdapter.includes("consultation-identity"), "consultation identity deduplication missing");
assert.ok(redisAdapter.includes('"metal-print:payments"'), "durable payment revenue ledger missing");
assert.ok(redisAdapter.includes("amountRefundedJpy"), "partial refund amount is not recorded");
assert.ok(redisAdapter.includes('`${input.editionId}|${input.orderId}`'), "refund payment mapping format mismatch");
assert.ok(webhookRoute.includes("charge.amount_refunded"), "Stripe refunded amount is not forwarded to ledger");
assert.ok(offerLocks.includes("approvalRegistry.editionApprovals"), "controlled made-to-order Offer approval registry missing");
assert.ok(
  offerLocks.includes("registryApprovals.get(editionId)"),
  "runtime Offer locks do not consume the per-Edition approval registry",
);
assert.ok(offerLocks.includes("registryApprovals.has(METAL_PRINT_PUBLIC_OFFER_EDITION_ID)"), "public Offer fail-closed invariant missing");
assert.ok(offerLocks.includes(": null"), "non-approved Offers are not safely closed");
assert.ok(offerLocks.includes("offer.approvalToken === expectedToken"), "runtime offer approval token gate missing");
assert.ok(offerLocks.includes("approvedAtMs <= Date.now()"), "runtime offer approval time gate missing");
assert.ok(consultationRoute.includes("checkoutAvailable"), "consultation response does not expose gated checkout availability");
assert.ok(consultationRoute.includes("checkoutAvailable: false"), "unverified consultation can expose Checkout");
assert.ok(checkoutRoute.includes("getApprovedMetalPrintOffer(editionId)"), "checkout availability bypasses the approved offer lock");
assert.ok(checkoutRoute.includes('shipping_address_collection'), "Stripe Checkout does not collect a shipping address");
assert.ok(checkoutRoute.includes('phone_number_collection'), "Stripe Checkout does not collect a delivery phone number");
assert.ok(checkoutRoute.includes('受注生産品です'), "Stripe Checkout is missing made-to-order disclosure");
for (const field of ["dossierAcceptedAt", "purchaseIntentConfirmedAt", "proofDisclosureAcceptedAt", "madeToOrderTermsAcceptedAt"]) {
  assert.ok(checkoutRoute.includes(field), `Stripe metadata is missing ${field}`);
  assert.ok(webhookRoute.includes(field), `signed webhook does not persist ${field}`);
  assert.ok(redisAdapter.includes(field), `durable payment ledger is missing ${field}`);
}
assert.ok(webhookRoute.includes("checkout acceptance evidence missing"), "paid webhook accepts incomplete customer acknowledgement evidence");
assert.ok(verificationRoute.includes('checkout.sessions.expire'), "production verifier does not expire Checkout before payment");
assert.ok(verificationRoute.includes('expiredSession.payment_intent !== null'), "production verifier does not measure PaymentIntent creation");
assert.ok(verificationRoute.includes('expiredSession.customer !== null'), "production verifier does not measure Customer creation");
assert.ok(webhookRoute.includes('recordMetalPrintProductionVerification'), "signed verification webhook is not persisted");
assert.ok(productionE2eRunner.includes('LIVE_ZERO_PAYMENT_CHECKOUT_EXPIRY_SIGNED_WEBHOOK_REDIS'), "production E2E evidence class missing");
assert.ok(consultationForm.includes('fetch("/api/metal-print/checkout"'), "qualified consultation has no checkout client path");
assert.ok(consultationForm.includes("consultationToken"), "checkout client does not forward the signed consultation token");
assert.ok(consultationForm.includes("qualified && checkoutAvailable"), "checkout UI is not gated by qualification and offer approval");
assert.ok(consultationResumeRoute.includes("Date.parse(consultation.expiresAt) <= Date.now()"), "expired consultation capability can resume Checkout");
assert.ok(consultationResumeRoute.includes("acceptanceComplete && Boolean(getApprovedMetalPrintOffer(editionId))"), "resume bypasses acceptance or Offer approval");
assert.ok(assuranceAudit.includes("LIVE_PROVIDER_READ_AND_EPHEMERAL_REDIS_CANARY"), "assurance audit ignores live provider connectivity evidence");
assert.ok(assuranceAudit.includes("providerConnectivityAgeMs <= 7 * 24 * 60 * 60 * 1000"), "provider connectivity evidence has no freshness boundary");
assert.ok(assuranceAudit.includes("matchingEnabledEndpoint === true"), "provider gate does not require an enabled Stripe webhook endpoint");
assert.ok(assuranceAudit.includes("canaryDeleted === true"), "provider gate does not require Redis canary cleanup");
assert.ok(connectivityProbe.includes("production-provider-connectivity-evidence.json"), "connectivity probe does not persist stable evidence");
assert.ok(connectivityProbe.includes("fs.writeFileSync(evidencePath"), "connectivity evidence is not persisted by the probe itself");
assert.ok(fulfillmentRoute.includes('authorization") !== `Bearer ${secret}`'), "fulfillment route lacks operator authorization");
assert.ok(fulfillmentRoute.includes("markMetalPrintFulfilled"), "fulfillment route does not persist the transition");
assert.ok(fulfillmentRoute.includes("trackingReferenceHash"), "fulfillment evidence hash missing");
assert.ok(fulfillmentRoute.includes("fulfillmentEvidenceSha256"), "fulfillment receipt hash missing");
assert.ok(fulfillmentRoute.includes("!/^[a-f0-9]{64}$/.test(trackingReferenceHash)"), "tracking evidence is not mandatory");
assert.ok(fulfillmentRoute.includes("!/^[a-f0-9]{64}$/.test(fulfillmentEvidenceSha256)"), "fulfillment receipt evidence is not mandatory");
assert.ok(redisAdapter.includes("record.fulfillmentEvidenceSha256 = ARGV[5]"), "fulfillment receipt hash is not persisted");
assert.ok(vendorOrderRunner.includes("paymentIntents.retrieve"), "customer-paid vendor preparation does not verify the live PaymentIntent");
assert.ok(vendorOrderRunner.includes("checkout.sessions.list"), "customer-paid vendor preparation does not bind the Checkout Session");
assert.ok(vendorOrderRunner.includes('mode: 0o600, flag: "wx"'), "customer delivery packet is not private and overwrite-safe");
assert.ok(!vendorOrderRunner.includes("whitewall.com"), "operator preparation must stop before vendor purchase");

console.log("metal-print production adapter: PASS — signed webhook, closed Offer, atomic inventory, and paid-order vendor preparation");
