name: weekly-digest

on:
  schedule: [{ cron: "0 7 * * 1" }]   # 月曜 07:00 UTC = Berlin 夏9:00/冬8:00
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Collect commits (last 7 days)
        run: |
          git log --since='7 days ago' --pretty=format:'- %h %s' > digest.md
          echo "" >> digest.md
          echo "## Next week (draft)" >> digest.md
          echo "- [ ] Top priority" >> digest.md
          echo "- [ ] Second" >> digest.md
          echo "- [ ] Validation" >> digest.md

      - name: Create weekly issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "週次ダイジェスト (${{ github.repository }}) - ${{ github.run_id }}"
          content-file: digest.md
          labels: report
          assignees: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
